In [3]:
# ch15_1.py
import cv2
img_rout = "C:\\Users\\STUST\\Desktop\\OPEN\\"
src = cv2.imread(img_rout + "easy.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [4]:
# ch15_1_1.py
import cv2

src = cv2.imread(img_rout + "easy.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像
cv2.imshow("src1",src)                              # 再輸出一次原始影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [5]:
# ch15_2.py
import cv2

src = cv2.imread(img_rout + "easy.jpg")
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)
print(f"資料類型      : {type(contours)}")
print(f"輪廓數量      : {len(contours)}")



資料類型      : <class 'tuple'>
輪廓數量      : 3


In [6]:
# ch15_3.py
import cv2
import numpy as np

src = cv2.imread(img_rout+"easy.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                                   # 回傳輪廓數
imgList = []                                        # 建立輪廓串列
for i in range(n):                                  # 依次繪製輪廓
    img = np.zeros(src.shape, np.uint8)             # 建立輪廓影像
    imgList.append(img)                             # 將預設黑底影像加入串列
    # 繪製輪廓影像
    imgList[i] = cv2.drawContours(imgList[i],contours,i,(255,255,255),5) 
    cv2.imshow("contours" + str(i),imgList[i])      # 顯示輪廓影像                      

cv2.waitKey(0)
cv2.destroyAllWindows()




In [7]:
# ch15_4.py
import cv2

src = cv2.imread(img_rout +"easy.jpg")
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                                   # 回傳輪廓數 
for i in range(n):                                  # 輸出輪廓的屬性
    print(f"編號 = {i}")
    print(f"輪廓點的數量 = {len(contours[i])}")
    print(f"輪廓點的外形 = {contours[i].shape}")





編號 = 0
輪廓點的數量 = 146
輪廓點的外形 = (146, 1, 2)
編號 = 1
輪廓點的數量 = 4
輪廓點的外形 = (4, 1, 2)
編號 = 2
輪廓點的數量 = 134
輪廓點的外形 = (134, 1, 2)


In [8]:
# ch15_5.py
import cv2

src = cv2.imread(img_rout+"easy.jpg")
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                                   # 回傳輪廓數 
print(contours[1])                                  # 列印編號1的輪廓點









[[[300  65]]

 [[300 152]]

 [[387 152]]

 [[387  65]]]


In [9]:
# ch15_6.py
import cv2

src = cv2.imread(img_rout+"easy1.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [11]:
# ch15_7.py
import cv2

src = cv2.imread(img_rout+"easy1.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [12]:
# ch15_8.py
import cv2

src = cv2.imread(img_rout+"lake.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,150,255,cv2.THRESH_BINARY)
cv2.imshow("binary",dst_binary)                     # 顯示二值化影像
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),2) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [15]:
# ch15_9.py
import cv2

src = cv2.imread(img_rout+"lake.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
cv2.imshow("binary",dst_binary)                     # 顯示二值化影像
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(255,255,255),-1) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [16]:
# ch15_10.py
import cv2
import numpy as np

src = cv2.imread(img_rout+"lake.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,150,255,cv2.THRESH_BINARY)
cv2.imshow("binary",dst_binary)                     # 顯示二值化影像
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)
mask = np.zeros(src.shape, np.uint8)
dst = cv2.drawContours(mask,contours,-1,(255,255,255),-1) # 繪製圖形輪廓
dst_result = cv2.bitwise_and(src,mask)
cv2.imshow("dst result",dst_result)                 # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [17]:
# ch15_11.py
import cv2

src = cv2.imread(img_rout+"easy2.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像
print(f"hierarchy 資料類型 : {type(hierarchy)}")
print(f"列印層級 \n {hierarchy}")

cv2.waitKey(0)
cv2.destroyAllWindows()




hierarchy 資料類型 : <class 'numpy.ndarray'>
列印層級 
 [[[ 1 -1 -1 -1]
  [-1  0 -1 -1]]]


In [19]:
# ch15_12.py
import cv2

src = cv2.imread(img_rout+"easy2.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像
print(f"hierarchy 資料類型 : {type(hierarchy)}")
print(f"列印層級 \n {hierarchy}")

cv2.waitKey(0)
cv2.destroyAllWindows()




hierarchy 資料類型 : <class 'numpy.ndarray'>
列印層級 
 [[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]


In [21]:
# ch15_13.py
import cv2

src = cv2.imread(img_rout+"easy3.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_CCOMP,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),3) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像
print(f"hierarchy 資料類型 : {type(hierarchy)}")
print(f"列印層級 \n {hierarchy}")

cv2.waitKey(0)
cv2.destroyAllWindows()




hierarchy 資料類型 : <class 'numpy.ndarray'>
列印層級 
 [[[ 1 -1 -1 -1]
  [-1  0  2 -1]
  [ 3 -1 -1  1]
  [-1  2 -1  1]]]


In [6]:
# ch15_14.py
import cv2

src = cv2.imread(img_rout+"01.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_TREE,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),3) # 繪製圖形輪廓
cv2.imshow("result",dst)                            # 顯示結果影像
print(f"列印層級 \n {hierarchy}")

cv2.waitKey(0)
cv2.destroyAllWindows()




列印層級 
 [[[-1 -1  1 -1]
  [ 2 -1 -1  0]
  [ 3  1 -1  0]
  [ 4  2 -1  0]
  [ 5  3 -1  0]
  [ 6  4 -1  0]
  [-1  5  7  0]
  [-1 -1 -1  6]]]


In [23]:
# ch15_15.py
import cv2
import numpy as np

src = cv2.imread(img_rout+"easy.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                                   # 回傳輪廓數
imgList = []                                        # 建立輪廓串列
for i in range(n):                                  # 依次繪製輪廓
    img = np.zeros(src.shape, np.uint8)             # 建立輪廓影像
    imgList.append(img)                             # 將預設黑底影像加入串列
    # 繪製輪廓影像
    imgList[i] = cv2.drawContours(imgList[i],contours,i,(255,255,255),5) 
    cv2.imshow("contours" + str(i),imgList[i])      # 顯示輪廓影像

for i in range(n):                                  # 列印輪廓面積
    area = cv2.moments(contours[i])
    print(f"輪廓面積 str(i) = {area['m00']}")
    
for i in range(n):                                  # 列印影像矩
    M = cv2.moments(contours[i])
    print(f"列印影像矩 {str(i)} \n {M}")

cv2.waitKey(0)
cv2.destroyAllWindows()




輪廓面積 str(i) = 4344.0
輪廓面積 str(i) = 7569.0
輪廓面積 str(i) = 5964.0
列印影像矩 0 
 {'m00': 4344.0, 'm10': 875551.0, 'm01': 534872.3333333333, 'm20': 178291996.0, 'm11': 107806662.83333333, 'm02': 67667946.66666666, 'm30': 36669616857.5, 'm21': 21974314231.166668, 'm12': 13638973452.333334, 'm03': 8756666917.5, 'mu20': 1821104.2870626152, 'mu11': 952.3539748340845, 'mu02': 1809656.3891702518, 'mu30': 32430.916221618652, 'mu21': 21016905.17049837, 'mu12': -12999.67679822445, 'mu03': -20861350.522485733, 'nu20': 0.09650619295080995, 'nu11': 5.04683104123893e-05, 'nu02': 0.09589953189865046, 'nu30': 2.6075622006486343e-05, 'nu21': 0.016898346973212075, 'nu12': -1.0452207272856162e-05, 'nu03': -0.01677327544654871}
列印影像矩 1 
 {'m00': 7569.0, 'm10': 2599951.5, 'm01': 821236.5, 'm20': 897857487.0, 'm11': 282094737.75, 'm02': 93878307.0, 'm30': 311693885601.75, 'm21': 97417537339.5, 'm12': 32247198454.5, 'm03': 11221786154.25, 'mu20': 4774146.75, 'mu11': 0.0, 'mu02': 4774146.75, 'mu30': 0.0, 'mu21': 0.0,

In [5]:
# ch15_16.py
import cv2

src = cv2.imread(img_rout+"01.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
dst = cv2.drawContours(src,contours,-1,(0,255,0),5) # 繪製圖形輪廓

for c in contours:                                  # 繪製中心點迴圈
    M = cv2.moments(c)                              # 影像矩
    Cx = int(M["m10"] / M["m00"])                   # 質心 x 座標
    Cy = int(M["m01"] / M["m00"])                   # 質心 y 座標
    cv2.circle(dst,(Cx,Cy),5,(255,0,0),-1)          # 繪製中心點
cv2.imshow("result",dst)                            # 顯示結果影像

cv2.waitKey(0)
cv2.destroyAllWindows()




In [25]:
# ch15_17.py
import cv2

src = cv2.imread(img_rout+"easy.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
n = len(contours)
for i in range(n):                                  # 繪製中心點迴圈
    M = cv2.moments(contours[i])                    # 影像矩
    area = cv2.contourArea(contours[i])             # 計算輪廓面積
    print(f"輪廓 {i} 面積 = {area}") 

cv2.waitKey(0)
cv2.destroyAllWindows()




輪廓 0 面積 = 4344.0
輪廓 1 面積 = 7569.0
輪廓 2 面積 = 5964.0


In [4]:
# ch15_18.py
import cv2

src = cv2.imread(img_rout+"01.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_EXTERNAL,
                      cv2.CHAIN_APPROX_SIMPLE)  
n = len(contours)
for i in range(n):                                  # 繪製中心點迴圈
    M = cv2.moments(contours[i])                    # 影像矩
    area = cv2.arcLength(contours[i],True)          # 計算輪廓周長
    print(f"輪廓 {i} 周長 = {area}") 

cv2.waitKey(0)
cv2.destroyAllWindows()




輪廓 0 周長 = 1885.12104845047


In [3]:
# ch15_19.py
import cv2

img_rout = "C:\\Users\\STUST\\Desktop\\OPEN\\"
src = cv2.imread(img_rout+"heart.jpg")
cv2.imshow("src",src)                               # 顯示原始影像

src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階
M = cv2.moments(src_gray)                           # 影像矩
nu20 = M['nu20']
print(f"歸一化中心矩 nu20 = {nu20}")
nu02 = M['nu02']
print(f"歸一化中心矩 nu02 = {nu02}")

Hu = cv2.HuMoments(M)                               # Hu矩
print(f"Hu \n {Hu}")                                # 列印Hu矩

result = Hu[0][0] - (nu20 + nu02)                   # 驗證Hu矩 0, h0
print(f"驗證結果 h0 - nu20 - nu02 = {result}")



cv2.waitKey(0)
cv2.destroyAllWindows()

歸一化中心矩 nu20 = 0.00047926293904721737
歸一化中心矩 nu02 = 0.00023866024885601934
Hu 
 [[ 7.17923188e-04]
 [ 5.78896885e-08]
 [ 6.81194047e-11]
 [ 2.42937256e-12]
 [-3.12515353e-23]
 [-5.84507960e-16]
 [ 1.53613252e-25]]
驗證結果 h0 - nu20 - nu02 = 0.0


In [4]:
#ch15_20.py
import cv2

src = cv2.imread(img_rout+ "3heart.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階

# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)

M0 = cv2.moments(contours[0])                       # 計算編號 0 影像矩 
M1 = cv2.moments(contours[1])                       # 計算編號 1 影像矩
M2 = cv2.moments(contours[2])                       # 計算編號 2 影像矩
Hu0 = cv2.HuMoments(M0)                             # 計算編號 0 Hu矩
Hu1 = cv2.HuMoments(M1)                             # 計算編號 1 Hu矩
Hu2 = cv2.HuMoments(M2)                             # 計算編號 2 Hu矩
# 列印Hu矩
print(f"h0 = {Hu0[0]}\t\t {Hu1[0]}\t\t {Hu2[0]}")
print(f"h1 = {Hu0[1]}\t\t {Hu1[1]}\t\t {Hu2[1]}")
print(f"h2 = {Hu0[2]}\t\t {Hu1[2]}\t\t {Hu2[2]}")
print(f"h3 = {Hu0[3]}\t\t {Hu1[3]}\t {Hu2[3]}")
print(f"h4 = {Hu0[4]}\t\t {Hu1[4]}\t {Hu2[4]}")
print(f"h5 = {Hu0[5]}\t\t {Hu1[5]}\t {Hu2[5]}")
print(f"h6 = {Hu0[6]}\t\t {Hu1[6]}\t {Hu2[6]}")

cv2.waitKey(0)
cv2.destroyAllWindows()


h0 = [0.18400164]		 [0.18362647]		 [0.18362647]
h1 = [0.00390046]		 [0.00388969]		 [0.00388969]
h2 = [0.00118707]		 [0.00115877]		 [0.00115877]
h3 = [4.41012234e-05]		 [4.27240647e-05]	 [4.27240647e-05]
h4 = [-1.00904583e-08]		 [-9.50599826e-09]	 [-9.50599826e-09]
h5 = [-2.75427701e-06]		 [-2.66455047e-06]	 [-2.66455047e-06]
h6 = [4.40391468e-11]		 [6.22527623e-11]	 [6.22527623e-11]


In [5]:
#ch15_21.py
import cv2

src = cv2.imread(img_rout+"3shapes.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)     # 影像轉成灰階

# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)

M0 = cv2.moments(contours[0])                       # 計算編號 0 影像矩 
M1 = cv2.moments(contours[1])                       # 計算編號 1 影像矩
M2 = cv2.moments(contours[2])                       # 計算編號 2 影像矩
Hu0 = cv2.HuMoments(M0)                             # 計算編號 0 Hu矩
Hu1 = cv2.HuMoments(M1)                             # 計算編號 1 Hu矩
Hu2 = cv2.HuMoments(M2)                             # 計算編號 2 Hu矩
# 列印Hu矩
print(f"h0 = {Hu0[0]}\t\t {Hu1[0]}\t\t {Hu2[0]}")
print(f"h1 = {Hu0[1]}\t\t {Hu1[1]}\t {Hu2[1]}")
print(f"h2 = {Hu0[2]}\t\t {Hu1[2]}\t {Hu2[2]}")
print(f"h3 = {Hu0[3]}\t\t {Hu1[3]}\t {Hu2[3]}")
print(f"h4 = {Hu0[4]}\t\t {Hu1[4]}\t {Hu2[4]}")
print(f"h5 = {Hu0[5]}\t\t {Hu1[5]}\t {Hu2[5]}")
print(f"h6 = {Hu0[6]}\t\t {Hu1[6]}\t {Hu2[6]}")

cv2.waitKey(0)
cv2.destroyAllWindows()




h0 = [0.18362125]		 [0.15949742]		 [0.18383141]
h1 = [0.00388853]		 [6.2205636e-05]	 [0.00388999]
h2 = [0.00115914]		 [1.09030421e-09]	 [0.00117116]
h3 = [4.25428614e-05]		 [8.53260565e-13]	 [4.34904474e-05]
h4 = [-9.44727464e-09]		 [1.09940012e-23]	 [-9.81486955e-09]
h5 = [-2.6528849e-06]		 [1.82308256e-16]	 [-2.7123853e-06]
h6 = [2.90666076e-11]		 [2.35891942e-23]	 [8.19693167e-11]


In [6]:
# ch15_22.py
import cv2

src = cv2.imread(img_rout+"myheart.jpg")
cv2.imshow("src",src)
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)         # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  

match0 = cv2.matchShapes(contours[0], contours[0],1,0)  # 輪廓0和0比較 
print(f"輪廓0和0比較 = {match0}")
match1 = cv2.matchShapes(contours[0], contours[1],1,0)  # 輪廓0和1比較
print(f"輪廓0和1比較 = {match1}")
match2 = cv2.matchShapes(contours[0], contours[2],1,0)  # 輪廓0和2比較
print(f"輪廓0和2比較 = {match2}")

cv2.waitKey(0)
cv2.destroyAllWindows()




輪廓0和0比較 = 0.0
輪廓0和1比較 = 0.00046299603915214704
輪廓0和2比較 = 0.29307592277155203


In [1]:
! pip install opencv-contrib-python

  Obtaining dependency information for opencv-contrib-python from https://files.pythonhosted.org/packages/aa/2e/576ac47f21d555b459ca837bb3fb937e50339b8fbfd294945ea2f5290416/opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/45.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.3 MB 991.0 kB/s eta 0:00:46
   ---------------------------------------- 0.1/45.3 MB 1.3 MB/s eta 0:00:35
   ---------------------------------------- 0.2/45.3 MB 1.5 MB/s eta 0:00:31
   ---------------------------------------- 0.3/45.3 MB 1.6 MB/s eta 0:00:29
   ---------------------------------------- 0.3/45.3 MB 1.5 MB/s eta 0:00:31
   ---------------------------------------- 0.4/45.3 MB 1.4 MB/s eta 0:00:32
    --------------------------------------- 0.6/45.3 MB 2.0 MB/s eta 0:00:22
    --------------------------------------- 0.8/45.3 MB 2.1 MB/s eta 0:00:21
    --------------------------------------- 0.9/45.3 MB 2.3 MB/s eta 0:00:2

In [2]:
# ch15_23.py
import cv2
img_rout = "C:\\Users\\STUST\\Desktop\\OPEN\\"
# 讀取與建立影像 1
src1 = cv2.imread(img_rout+"mycloud1.jpg")
cv2.imshow("mycloud1",src1)
src1_gray = cv2.cvtColor(src1,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src1_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt1 = contours[0]
# 讀取與建立影像 2
src2 = cv2.imread(img_rout+"mycloud2.jpg")
cv2.imshow("mycloud2",src2)
src2_gray = cv2.cvtColor(src2,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
ret, dst_binary = cv2.threshold(src2_gray,127,255,cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt2 = contours[0]
# 讀取與建立影像 3
src3 = cv2.imread(img_rout+"explode1.jpg")
cv2.imshow("explode",src3)
src3_gray = cv2.cvtColor(src3,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
ret, dst_binary = cv2.threshold(src3_gray,127,255,cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt3 = contours[0]
sd = cv2.createShapeContextDistanceExtractor()          # 建立形狀場景運算子
match0 = sd.computeDistance(cnt1, cnt1)                 # 影像1和1比較 
print(f"影像1和1比較 = {match0}")
match1 = sd.computeDistance(cnt1, cnt2)                 # 影像1和2比較
print(f"影像1和2比較 = {match1}")
match2 =sd.computeDistance(cnt1, cnt3)                  # 影像1和3比較
print(f"影像1和3比較 = {match2}")


cv2.waitKey(0)
cv2.destroyAllWindows()




影像1和1比較 = 0.0
影像1和2比較 = 0.22617380321025848
影像1和3比較 = 0.8256409168243408


In [3]:
# ch15_24.py
import cv2

# 讀取與建立影像 1
src1 = cv2.imread(img_rout+"mycloud1.jpg")
cv2.imshow("mycloud1",src1)
src1_gray = cv2.cvtColor(src1,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
# 二值化處理影像
ret, dst_binary = cv2.threshold(src1_gray,127,255,cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt1 = contours[0]
# 讀取與建立影像 2
src2 = cv2.imread(img_rout+"mycloud2.jpg")
cv2.imshow("mycloud2",src2)
src2_gray = cv2.cvtColor(src2,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
ret, dst_binary = cv2.threshold(src2_gray,127,255,cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt2 = contours[0]
# 讀取與建立影像 3
src3 = cv2.imread(img_rout+"explode1.jpg")
cv2.imshow("explode",src3)
src3_gray = cv2.cvtColor(src3,cv2.COLOR_BGR2GRAY)       # 影像轉成灰階
ret, dst_binary = cv2.threshold(src3_gray,127,255,cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                      cv2.RETR_LIST,
                      cv2.CHAIN_APPROX_SIMPLE)  
cnt3 = contours[0]
hd = cv2.createHausdorffDistanceExtractor()             # 建立Hausdorff
match0 = hd.computeDistance(cnt1, cnt1)                 # 影像1和1比較 
print(f"影像1和1比較 = {match0}")
match1 = hd.computeDistance(cnt1, cnt2)                 # 影像1和2比較
print(f"影像1和2比較 = {match1}")
match2 =hd.computeDistance(cnt1, cnt3)                  # 影像1和3比較
print(f"影像1和3比較 = {match2}")
cv2.waitKey(0)
cv2.destroyAllWindows()




影像1和1比較 = 0.0
影像1和2比較 = 12.206555366516113
影像1和3比較 = 8.5440034866333
