In [6]:
# ch12_4.py
import cv2
import numpy as np
image_path = "C:\\Users\\henry\\Desktop\\ch12\\"
src = cv2.imread(image_path + "whilster.jpg")
kernel = np.ones((3,3),np.uint8)        # 建立3x3內核
dst1 = cv2.erode(src, kernel)           # 腐蝕操作
kerne2 = np.ones((5,5),np.uint8)        # 建立5x5內核
dst2 = cv2.erode(src, kerne2)           # 腐蝕操作

cv2.imshow("src",src)
cv2.imshow("after erosion 3 x 3",dst1)
cv2.imshow("after erosion 5 x 5",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
src = np.zeros((7,7),np.uint8) 
src[2:5,2:5] = 1                    # 建立前景影像
kernel = np.ones((3,3),np.uint8)    # 建立內核
dst = cv2.dilate(src, kernel)       # 膨脹操作
print(f"src = \n {src}")
print(f"kernel = \n {kernel}")
print(f"Dilation = \n {dst}")

src = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Dilation = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [8]:
src = np.zeros((7,7),np.uint8) 
src[1:6,1:6] = 1                    # 建立前景影像
kernel = np.ones((3,3),np.uint8)    # 建立內核
dst = cv2.erode(src, kernel)        # 腐蝕操作
print(f"src = \n {src}")
print(f"kernel = \n {kernel}")
print(f"Erosion = \n {dst}")

src = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Erosion = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [11]:
src = cv2.imread(image_path + "night.jpg")
kernel = np.ones((9,9),np.uint8)                    # 建立9x9內核
dst = cv2.morphologyEx(src,cv2.MORPH_OPEN,kernel)   # 開運算

cv2.imshow("src",src)
cv2.imshow("after Opening 9 x 9",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
src = cv2.imread(image_path +"bw.jpg")
kernel = np.ones((5, 5),np.uint8)       # 建立5x5內核
dst1 = cv2.erode(src, kernel)           # 腐蝕操作
kerne2 = np.ones((11, 11),np.uint8)     # 建立11x11內核
dst2 = cv2.erode(src, kerne2)           # 腐蝕操作

cv2.imshow("src",src)
cv2.imshow("after erosion 5 x 5",dst1)
cv2.imshow("after erosion 11 x 11",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
src = cv2.imread(image_path + "night.jpg")
kernel = np.ones((9,9),np.uint8)                # 建立9x9內核
mid = cv2.dilate(src, kernel)                   # dilation
dst = cv2.erode(mid, kernel)                    # erosion
cv2.imshow("src",src)
cv2.imshow("after dilation 9 x 9",mid)
cv2.imshow("after erosion 9 x 9",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
src = cv2.imread(image_path + "a.jpg")
kernel = np.ones((3, 3),np.uint8)       # 建立3x3內核
dst1 = cv2.dilate(src, kernel)          # 膨脹操作
kerne2 = np.ones((5, 5),np.uint8)       # 建立5x5內核
dst2 = cv2.dilate(src, kerne2)          # 膨脹操作

cv2.imshow("src",src)
cv2.imshow("after dilation 3 x 3",dst1)
cv2.imshow("after dilation 5 x 5",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [16]:
src = cv2.imread(image_path +"btree.jpg")
kernel = np.ones((3,3),np.uint8)                    # 建立3x3內核
dst = cv2.morphologyEx(src,cv2.MORPH_TOPHAT,kernel) # tophat

cv2.imshow("src",src)
cv2.imshow("after tophat",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
src = cv2.imread(image_path+ "snowman.jpg")
kernel = np.ones((11,11),np.uint8)                      # 建立11x11內核
dst = cv2.morphologyEx(src,cv2.MORPH_BLACKHAT,kernel)   # blackhat

cv2.imshow("src",src)
cv2.imshow("after blackhat",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
src = cv2.imread(image_path + "snowman1.jpg")
kernel = np.ones((11,11),np.uint8)                  # 建立11x11內核
dst = cv2.morphologyEx(src,cv2.MORPH_CLOSE,kernel)  # 閉運算

cv2.imshow("src",src)
cv2.imshow("after Closing 11 x 11",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()